
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartHawker' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartHawker
  pod 'SwiftMoment'
  pod 'Localize-Swift', '1.5’
  pod 'Charts'
  pod 'IQKeyboardManagerSwift', '4.0.5'
  pod 'FontAwesome-iOS'
  pod 'JTAppleCalendar'
  pod 'Material’, :git => 'https://github.com/CosmicMind/Material.git', :branch => 'swift-2.3'

  target 'SmartHawkerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmartHawkerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = ‘2.3’
    end
  end
end