# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartHawker' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartHawker
  pod "CalendarView"
  pod 'Localize-Swift', '~> 1.5’
  pod 'Charts'
  pod 'DLRadioButton', '~> 1.4'

  target 'SmartHawkerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmartHawkerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
